### ISSUE TITLE
Invalid Snowflake account produces invalid URL, unhandledPromiseRejection, and swallows error

### ISSUE THREAD

**Issue by markandrus** [snowflakedb/snowflake-connector-nodejs#537] opened 2023-06-15 11:13 UTC
## Reproduction

You can put this test.js file in the root of the repo to reproduce:

```js
// test.js

const snowflake = require('.') // or require('snowflake-sdk')

process.on('unhandledRejection', err => {
  // This should not execute, but it does, because the error is not handled by snowflake-sdk.
  console.error('unhandledRejection', err)
})

const connection = snowflake.createConnection({
  account: 'This produces an invalid URL',
  database: 'Snowflake Database',
  password: 'Snowflake Password',
  role: 'Snowflake Role',
  schema: 'Snowflake Schema',
  username: 'Snowflake User',
  warehouse: 'Snowflake Warehouse'
})

connection.connect(err => {
  // This should execute, but it does not.
  console.error('connection.connect', err)
})
```

```
$ node test.js
(node:316) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
unhandledRejection TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:400:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at Object.requestWithCallback (snowflake-connector-nodejs/node_modules/urllib/lib/urllib.js:233:33)
    at Object.request (snowflake-connector-nodejs/node_modules/urllib/lib/urllib.js:154:20)
    at NodeHttpClient.sendRequest (snowflake-connector-nodejs/lib/http/base.js:98:33)
    at Gzip.cb (snowflake-connector-nodejs/lib/http/base.js:145:7)
    at Gzip.zlibBufferOnEnd (node:zlib:161:10)
    at Gzip.emit (node:events:513:28)
    at Gzip.emit (node:domain:489:12) {
  input: 'https://This produces an invalid URL.snowflakecomputing.com/session/v1/login-request?requestId=e6c95558-2d57-408b-b6a1-ac08e3f483af&warehouse=Snowflake%20Warehouse&databaseName=Snowflake%20Database&schemaName=Snowflake%20Schema&roleName=Snowflake%20Role',
  code: 'ERR_INVALID_URL'
}
```

### 1. Improve URL parsing

snowflake-sdk should probably ensure the URLs it constructs are valid, and fail early (perhaps with a synchronous exception) if not. I don't know all the places in the snowflake-sdk that construct URLs, but my particular error arises (in part) [here](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/connection/connection_config.js#L76-L83):

```js
    if (dotPos < 0 && Util.isString(options.region) && options.region.length > 0)
    {
      options.accessUrl = Util.format('https://%s.%s.snowflakecomputing.com', options.account, options.region);
    }
    else
    {
      options.accessUrl = Util.format('https://%s.snowflakecomputing.com', options.account);
    }
```

Notice that the URLs aren't validated, they're just formatted strings, so the resulting `accessUrl` is

```
https://This produces an invalid URL.snowflakecomputing.com/session/v1/login-request?requestId=e6c95558-2d57-408b-b6a1-ac08e3f483af&warehouse=Snowflake%20Warehouse&databaseName=Snowflake%20Database&schemaName=Snowflake%20Schema&roleName=Snowflake%20Role
```

### 2. `try`/`catch` around `require('urllib').request`

We could also put a `try`/`catch` [here](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/http/base.js#L100-L116) in `lib/http/base.js` like this:

```js
  try {
    request = require('urllib').request(requestOptions.url, requestOptions, async function (err, data, response)
      {
        // if a callback has been specified, normalize the
        // response before passing it to the callback
        if (Util.isFunction(options.callback))
        {
          if (err)
          {
            await options.callback(err, normalizeResponse(null), null);
          }
          else
          {
            response.body = response.data.toString();
            await options.callback(null, normalizeResponse(response), data.toString());
          }
        }
      });
  } catch (err) {
    if (Util.isFunction(options.callback))
    {
      // This will lead to retries, which we do not want in the case of INVALID_URL.
      await options.callback(err, normalizeResponse(null), null);
    }
  }
```

But this will lead to retries, which we do not want in the case of INVALID_URL. Instead, we'd like to error early.

**Comment by sfc-gh-dszmolka** [comment] 2023-06-15 11:41
hi and thank you for raising this issue! it is surely not a bug - it's the responsibility of the user to provide the account as [per the documented format](https://docs.snowflake.com/en/user-guide/admin-account-identifier). (either regionless: `myorg-myaccount` , or the locator version e.g. `myaccount.us-east-2.aws`)

but, i agree there's also room for improvement or at least handle these user errors more gracefully, so we'll take a look. appreciate your inputs for the possible ways forward !

**Comment by markandrus** [comment] 2023-06-15 12:19
@sfc-gh-dszmolka thank you for your response. In our application, we receive the account from the end user and pass it along to snowflake-sdk. It is untrusted input, so is there a function in snowflake-sdk that can validate the account string?

**Comment by sfc-gh-dszmolka** [comment] 2023-06-15 12:54
at this moment of writing, I'm not aware of such validation for `account` (except it [needing to be a string](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/v1.6.23/lib/connection/connection_config.js#L59)) so if it's really coming from an upper layer, at this moment I guess you'll need to validate it at the application layer before passing it on to `snowflake-sdk`.

**Comment by sfc-gh-dszmolka** [comment] 2023-11-09 13:37
should be resolved with https://github.com/snowflakedb/snowflake-connector-nodejs/pull/692 , review in progress

**Comment by sfc-gh-dszmolka** [comment] 2023-11-13 09:53
#692 merged into `main` and will be part of the next upcoming release. will update this issue once the release is out.

**Comment by sfc-gh-dszmolka** [comment] 2023-11-15 18:47
node.js driver version 1.9.1 released with the fix and is available on npm. thank you all for bearing with us !

**Closed by sfc-gh-dszmolka** 2023-11-15 18:47 UTC
Labels: enhancement, Fixed - Awaiting Release
