### ISSUE TITLE
SNOW-897216: Package should declare dependency on asn1.js

### ISSUE THREAD

**Issue by ajwootto** [snowflakedb/snowflake-connector-nodejs#624] opened 2023-08-21 22:11 UTC
1. What version of NodeJS driver are you using?
1.7.0
   
2. What operating system and processor architecture are you using?

   Mac OS Apple Silicon
3. What version of NodeJS are you using?
(`node --version` and `npm --version`)
18.16

Installing this package using a stricter package manager such as `pnpm` or yarn in `pnpm` mode will result in an error from the 
`asn1.js-rfc2560` dependency when it attempts to resolve `asn1.js`. This is because the `asn1.js-rfc2560` package declares asn1.js as a peerDependency, but this package does not supply it with one. The reason this works fine in regular `npm` installs is because the other asn1-related dependency this package asks for (`asn1.js-rfc5280`) declares a direct dependency on `asn1.js`. It is then installed, and with `npm` it gets "hoisted" to the root of `node_modules/` allowing the other package with the peer dependency to find it. `pnpm` does not allow this type of hoisting, so this package needs to declare a direct dependency on `asn1.js` in order to work.

**Comment by sfc-gh-dszmolka** [comment] 2023-08-22 08:11
hi and thank you for raising this issue and appreciate the detailed explanation! 

i wanted to see for myself but I'm obviously missing something, because I could not reproduce in a `node:18` container.
steps I've taken:
1. install `pnpm`
2. install `snowflake-sdk`

```shell
# node -v
v18.16.1
# curl -fsSL https://get.pnpm.io/install.sh | bash -
==> Downloading pnpm binaries 8.6.12
..gets installed..

# pnpm install snowflake-sdk    
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.1.0: 16.38 kB/10.87 MB
 WARN  deprecated string-similarity@4.0.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
 WARN  deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
Packages: +221
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 221, reused 0, downloaded 221, added 221, done

dependencies:
+ snowflake-sdk 1.7.0

Downloading registry.npmjs.org/aws-sdk/2.1441.0: 10.87 MB/10.87 MB, done
Done in 7.8s

# pnpm why asn1.js
Legend: production dependency, optional only, dev only

/node

dependencies:
snowflake-sdk 1.7.0
├─┬ @techteamer/ocsp 1.0.0
│ ├── asn1.js 5.4.1
│ ├─┬ asn1.js-rfc2560 5.0.1
│ │ ├── asn1.js 5.4.1 peer
│ │ └─┬ asn1.js-rfc5280 3.0.0
│ │   └── asn1.js 5.4.1
│ └─┬ asn1.js-rfc5280 3.0.0
│   └── asn1.js 5.4.1
├─┬ asn1.js-rfc2560 5.0.1
│ ├── asn1.js 5.4.1 peer
│ └─┬ asn1.js-rfc5280 3.0.0
│   └── asn1.js 5.4.1
└─┬ asn1.js-rfc5280 3.0.0
  └── asn1.js 5.4.1
  ```

even with `pnpm config set strict-peer-dependencies true` , `snowflake-sdk` gets installed correctly.
with our without the above setting, after installation, i'm able to run the example script to connect to SF and fetch data.

can you perhaps provide the reproduction steps or what other setting i need to look at ? thank you in advance !

**Comment by ajwootto** [comment] 2023-08-22 14:14
Hi @sfc-gh-dszmolka thanks for taking a look!

In my original post I said that using `pnpm` would trigger the issue, but I was actually using `yarn` with the `nodeLinker` option set to `pnpm`. I assumed the two things would be equivalent but it appears they are not. Sorry for the confusion.

My actual repro steps are.
1. Create a new project
2. ensure yarn is using the latest 3.x version with `yarn set version stable`
3. change or create a `.yarnrc.yml` file with the line `nodeLinker: pnpm`
4. run `yarn install`
5. check node_modules/ folder

This is what I see in the node_modules directory afterwards:
<img width="395" alt="image" src="https://github.com/snowflakedb/snowflake-connector-nodejs/assets/1740731/8d80ed05-9b6b-49e3-8d5e-30c4ead1f6d7">
Notably the `asn1.js` package is missing from the `node_modules/` of `asn1.js-rfc2560` and also does not appear at the top-level `node_modules/`

I'm actually unsure at this point whether this would be considered a bug in yarn itself, though it does seem intuitively correct to me that it shouldn't satisfy a peer requirement of one package with a subdependency of another

**Comment by sfc-gh-dszmolka** [comment] 2023-08-23 07:14
thank you @ajwootto ; makes sense and of course thanks to your repro, it easily reproduces for me as well. As an interim solution, I could avoid the warning (and also, get `asn1.js` installed) by simply adding it to the devDependencies of `snowflake-sdk`:
```json
  "devDependencies": {
    "asn1.js": "^5.0.0",   <<< new line added
    "async": "^3.2.3",
```

perhaps it can be used as a workaround. Anyways, we'll take a look.

**Comment by ajwootto** [comment] 2023-08-23 13:16
@sfc-gh-dszmolka glad you could get a repro!

I don't think adding it to devDependencies will fix the issue though since as far as I know it's being used at runtime, so I think it needs to go in dependencies.

**Comment by HarlemSquirrel** [comment] 2023-09-27 14:44
I was able to work around this by adding the following to my `.yarnrc.yml`

```yml
packageExtensions:
  snowflake-sdk@*:
    dependencies:
      "asn1.js": "^5.0.0" # https://github.com/snowflakedb/snowflake-connector-nodejs/issues/624
```

**Comment by sfc-gh-dszmolka** [comment] 2023-09-29 05:32
PR with the fix: https://github.com/snowflakedb/snowflake-connector-nodejs/pull/654

**Comment by sfc-gh-dszmolka** [comment] 2023-09-30 06:25
PR is merged and will be part of the October release, expected towards end of October. 
We ended up going with the approach of peer-depending `asn1.js`, which eliminates the error described in this Issue, confirmed with re-running the reproduction pre and post change.

**Comment by sfc-gh-dszmolka** [comment] 2023-11-15 18:47
node.js driver version 1.9.1 released with the fix and is available on npm. thank you all for bearing with us !

**Closed by sfc-gh-dszmolka** 2023-11-15 18:47 UTC
Labels: bug, Fixed - Awaiting Release

**Comment by HarlemSquirrel** [comment] 2023-11-21 14:42
I'm still seeing this issue with the version 1.9.1 when I remove my above workaround.

```
yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ my-proj@workspace:. doesn't provide asn1.js (p2c9f1), requested by snowflake-sdk
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 205ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 286ms
➤ YN0000: Done with warnings in 0s 809ms

yarn explain peer-requirements p2c9f1
➤ YN0000: my-proj@workspace:. doesn't provide asn1.js, breaking the following requirements:

➤ YN0000: asn1.js-rfc2560@npm:5.0.1 [88ff7] → ^5.0.0 ✘
➤ YN0000: snowflake-sdk@npm:1.9.1 [9dccf]   → ^5.4.1 ✘

➤ YN0000: Note: these requirements start with snowflake-sdk@npm:1.9.1 [9dccf]
```

**Comment by sfc-gh-dszmolka** [comment] 2023-11-21 15:23
the snowflake-sdk package declares peerDependency on asn1.js , as mentioned in previous comments
> We ended up going with the approach of peer-depending asn1.js, which eliminates the error described in this Issue, confirmed with re-running the reproduction pre and post change.

meaning after a long discussion (as i remember it) the decision was to rely on the project which uses `snowflake-sdk` as a dependency, the same project to provide the runtime environment with `asn1.js`

**Comment by HarlemSquirrel** [comment] 2023-11-21 15:29
So the installation instructions should be updated to include this as well?
