### ISSUE TITLE
SNOW-976425: Getting no active warehouse in the session when trying to query

### ISSUE THREAD

**Issue by akshaysasidrn** [snowflakedb/snowflake-connector-nodejs#708] opened 2023-11-22 09:09 UTC
1. What version of NodeJS driver are you using?
v1.6.23
   
2. What operating system and processor architecture are you using?
`node:18.3.0-buster` image for x86
   
3. What version of NodeJS are you using?
18.3.0

4. What are the component versions in the environment (`npm list`)?
 @types/snowflake-sdk@^1.6.12
 snowflake-sdk@^1.6.23

5.Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

`CURRENT_VERSION(): "7.41.0"`

6. What did you do?

I'm creating a connection with explicitly mentioned warehouse to snowflake. This connection is then stored in memory.
https://github.com/ToolJet/ToolJet/blob/develop/plugins/packages/snowflake/lib/index.ts#L70
After a certain point of time, the connection gets no active warehouse in the session error.

What we have tried so far:
- Tried using use warehouse xyz when the connection loses active warehouse. But we get the same not active warehouse error.
- Tried recreating a new connection to the warehouse. Then tried running a query with the newly created connection to find it also has no active warehouse in connection error.

7. What did you expect to see?
Given that warehouse is explicitly mentioned, did not expect to see active warehouse

8. Can you set logging to DEBUG and collect the logs?
No I don't have access to do that.
   
9. What is your Snowflake account identifier, if any? (Optional)

**Comment by sfc-gh-dszmolka** [comment] 2023-11-22 09:18
seems to be duplicate of https://github.com/snowflakedb/snowflake-connector-nodejs/issues/707

**Closed** 2023-11-22 09:18 UTC
Labels: duplicate
