### ISSUE TITLE
https-proxy-agent module not found

### ISSUE THREAD

**Issue by bibli-alex** [snowflakedb/snowflake-connector-nodejs#343] opened 2022-08-26 01:07 UTC
[This PR](https://github.com/snowflakedb/snowflake-connector-nodejs/pull/276) removed `https-proxy-agent` from the list of dependencies. You still require it within the `https_proxy_ocsp_agent.js` file at [this line](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/f10ef25195d092f3324f6bdfb9cca127ffc52e00/lib/agent/https_proxy_ocsp_agent.js#L13)

This causes dependency issues.

**Comment by mscott5861** [comment] 2022-10-14 13:01
I'm seeing this issue as well.

**Comment by MattCorwin** [comment] 2022-11-11 21:54
Same here

**Comment by sfc-gh-dszmolka** [comment] 2023-01-18 08:58
thank you for reporting this issue. #293 and #343 look similar, in a way that both of them are caused by the missing dependencies. seems to be still missing in the latest version of the driver (1.6.17 now), we'll take a look.

**Comment by sfc-gh-dszmolka** [comment] 2023-04-26 17:25
#482

**Comment by sfc-gh-dszmolka** [comment] 2023-05-25 06:44
fix released with version [1.6.22](https://github.com/snowflakedb/snowflake-connector-nodejs/releases/tag/v1.6.22)

**Closed by sfc-gh-dszmolka** 2023-05-25 06:44 UTC
Labels: bug
