### ISSUE TITLE
SNOW-895093: Excessive logging about OCSP failure

### ISSUE THREAD

**Issue by bryandrenner** [snowflakedb/snowflake-connector-nodejs#621] opened 2023-08-17 18:30 UTC
I'm using `snowflake-sdk` in an API (web service) product. About 35 hours after the service is (re)started, the Snowflake SDK starts logging a large volume of entries like:

```
WARNING!!! using fail-open to connect. Driver is connecting to an HTTPS endpoint without OCSP based Certificated Revocation checking as it could not obtain a valid OCSP Response to use from the CA OCSP responder. Details: OCSPError: Invalid validity. Valid from: 2023-08-14T14:41:47.000Z , Valid to: 2023-08-16T02:41:47.000Z"
```

The thousands of subsequent log entries are identical to the above, including "valid from" and "valid to" values that do not change for the lifespan of the application. The "valid to" timestamp is always in the recent past.

My hypothesis is that the Snowflake SDK caches an OCSP response and continues to use it even after it is no longer valid, but it should instead fetch an updated OCSP response.

1. What version of NodeJS driver are you using?

1.6.19
   
2. What operating system and processor architecture are you using?

Alpine Linux v13.18.2, x86_64
   
3. What version of NodeJS are you using?

18.16.4

4. What are the component versions in the environment (`npm list`)?

```
├── @aws-sdk/client-secrets-manager@3.358.0
├── @js-joda/core@5.5.3
├── @js-joda/locale@4.8.10
├── @js-joda/timezone@2.18.0
├── @nestjs/axios@2.0.0
├── @nestjs/cli@9.5.0
├── @nestjs/common@9.3.9
├── @nestjs/config@2.3.1
├── @nestjs/core@9.3.9
├── @nestjs/platform-express@9.3.9
├── @nestjs/schematics@9.0.4
├── @nestjs/testing@9.3.9
├── @types/express-session@1.17.7
├── @types/express@4.17.17
├── @types/jest@29.2.4
├── @types/jsonwebtoken@9.0.1
├── @types/lodash@4.14.194
├── @types/node@18.11.18
├── @types/plotly.js@2.12.18
├── @types/snowflake-sdk@1.6.12
├── @types/supertest@2.0.12
├── @typescript-eslint/eslint-plugin@5.54.1
├── @typescript-eslint/parser@5.54.1
├── axios@1.3.4
├── class-transformer@0.5.1
├── class-validator@0.14.0
├── connect-redis@7.0.1
├── eslint-config-prettier@8.7.0
├── eslint-plugin-prettier@4.2.1
├── eslint@8.35.0
├── express-session@1.17.3
├── jest@29.3.1
├── joi@17.8.3
├── jsonwebtoken@9.0.0
├── prettier@2.8.4
├── redis@4.6.5
├── reflect-metadata@0.1.13
├── rxjs@7.8.1
├── snowflake-sdk@1.6.19
├── source-map-support@0.5.21
├── supertest@6.3.3
├── ts-jest@29.0.3
├── ts-loader@9.4.2
├── ts-node@10.9.1
├── tsconfig-paths@4.1.1
├── typescript@4.9.5
└── vue-i18n@9.2.2
```

6.Server version:* E.g. 1.90.1

7.28.0

7. What did you do?

I consume the SDK generally as follows, sanitized:

```ts
const connection = createConnection({
  account: ourAppConfig.account,
  username: ourAppConfig.username,
  database: ourAppConfig.database,
  warehouse: ourAppConfig.warehouse,
  schema: ourAppConfig.schema,
  password: ourAppConfig.snowflakePassword,
})

await new Promise((resolve, reject) => {
  connection.connect((err, conn) => {
    if (err) {
      reject(err)
    }
    resolve(conn)
  })
})

await new Promise((resolve, reject) => {
  connection.execute({
    sqlText: ourQuery,
    streamResult: false,
    fetchAsString: ourFetchAsString,
    complete: (err, stmt, rows) => {
      if (err) {
        reject({
          context: stmt.getSqlText(),
          err,
        })
      } else {
        resolve({ stmt, rows })
      }
    },
  })
})
```

The service keeps a reference to the open connection and reuses it for subsequent requests.

8. What did you expect to see?

Few OCSP warnings in our logs.

**Comment by sfc-gh-dszmolka** [comment] 2023-08-17 18:42
hi and thank you for raising this issue ! i think it is a duplicate of Issue https://github.com/snowflakedb/snowflake-connector-nodejs/issues/371 which was fixed with #442 and #457 , and the fix PRs released with driver version 1.6.21
please try to upgrade to at least 1.6.21 and this issue should not reproduce anymore.

**Closed by sfc-gh-dszmolka** 2023-08-17 18:42 UTC
Labels: bug
