### ISSUE TITLE
Support variable binding for `LIKE` expressions in DDL Commands (e.g. `SHOW <objects>`)

### ISSUE THREAD

**Issue by APTy** [snowflakedb/snowflake-connector-nodejs#387] opened 2022-12-22 16:03 UTC
## Problem
Current usage of a `?` in a [`SHOW OBJECTS LIKE ?`](https://docs.snowflake.com/en/sql-reference/sql/show-objects.html) command fails with:

```
Call failed. Error [OperationFailedError]: SQL compilation error:
syntax error line 1 at position 18 unexpected '?'.
```

This is apparent, since even this codebase uses `util.format` with simple string replacement for these statements:

https://github.com/snowflakedb/snowflake-connector-nodejs/blob/0c7eea1c3056c54f1a1a7b18b57a683393b8cb5b/system_test/testSystemSetWhSnowflakeSupportFlag.js#L163-L164

## Long Term Solution
Is variable binding done at the client or server layer?

I'm happy to contribute here if it's even possible on the client side.

## Short Term Solution
For now, I will likely use simple (insecure) string replacement, with a strict regex based on [Snowflake's Identifier Requirements](https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html):

> Start with a letter (A-Z, a-z) or an underscore (“_”).
> Contain only letters, underscores, decimal digits (0-9), and dollar signs (“$”).

Something like this:
```javascript
const newShowObjectQuery = (objectId: string) => {
  if (!(/^[\w$]+$/.test(objectId))) { // https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html
    throw new Error("show objects: invalid objectId");
  }
  return `SHOW OBJECTS LIKE '${objectId}' IN IDENTIFIER(?);`;
};
```

## Thanks
This library has been super valuable for me, so just wanted to say I appreciate its existence and any help anyone can offer!

**Comment by sfc-gh-dszmolka** [comment] 2023-01-19 09:41
hi, thank you for reporting this issue. it reproduces quite easily and at the first glance seems to be related to #315 , or at least they both might be caused by the same underlying issue/lack of capability. we'll take a look and see how best move forward.

**Comment by sfc-gh-dszmolka** [comment] 2023-05-26 08:16
this feature as it turns out, is not supported on the Snowflake backend. At this moment there's no timeline available when the server-side support will be available. Therefore, closing this issue for now.

Internally, we're tracking this request and can reopen again if and when the server-side support will be implemented.

**Closed by sfc-gh-dszmolka** 2023-05-26 08:16 UTC
Labels: enhancement, In Progress
