### ISSUE TITLE
Unhandled exception after replacing eval for betterEval

### ISSUE THREAD

**Issue by dsandi** [snowflakedb/snowflake-connector-nodejs#539] opened 2023-06-15 17:34 UTC
1. What version of NodeJS driver are you using?
1.6.21
   
2. What operating system and processor architecture are you using?
Ubuntu 22.04.2
   
3. What version of NodeJS are you using?
v18.14.2

4. What are the component versions in the environment (`npm list`)?

5.Server version:* 
7.20.0

6. What did you do?

I execute a query that includes these columns: 

ifnull(price::number, PARSE_JSON('null')))) AS "my_column_1",
PARSE_JSON('[]') AS "my_column_2",

```
    connection.execute({
      sqlText: `my query`,
      complete: function (err, stmt) {
        if (err) {
          console.error("Failed to execute statement due to the following error: " + err.message);
        } else {
          console.log("Successfully executed statement: " + stmt.getSqlText());
        }
      }
    });
```
    
7. What did you expect to see?

I expect the complete callback to be invoked with either the data or an error

What should have happened and what happened instead?

If there was an error parsing I should get the error back, but i get an unhandled exception:

```evalmachine.<anonymous>:7:23 clearContext
evalmachine.<anonymous>:19:4
node:vm:141:12 Script.runInContext
node:vm:146:17 Script.runInNewContext
node:vm:300:38 Object.runInNewContext
srv/app/paapi/src/node_modules/better-eval/src/core.js:37:6 betterEval
srv/app/paapi/src/node_modules/snowflake-sdk/lib/connection/result/column.js:555:13 Object.convertRawVariant [as convert]
srv/app/paapi/src/node_modules/snowflake-sdk/lib/connection/result/column.js:788:19 Column.extractFromRow
srv/app/paapi/src/node_modules/snowflake-sdk/lib/connection/result/column.js:235:27 Column.getRowValue
```

Seems like `betterEval` can throw exceptions that `eval` didn't and they are not propagated so they go unhandled and kill the node process.

The issue appeared after this was published: https://github.com/snowflakedb/snowflake-connector-nodejs/pull/465/files

**Comment by sfc-gh-dszmolka** [comment] 2023-06-28 18:33
#536 is now merged and will be part of the next release, expected in second half of July. it completely removes `better-eval` .

**Comment by sfc-gh-dszmolka** [comment] 2023-07-27 18:56
PR is released as part of the latest Snowflake Node.JS driver version 1.7.0. Closing this issue.

**Comment by dsandi** [comment] 2023-07-27 19:48
Was this published to npm already? @sfc-gh-dszmolka 

It is not showing for me:

https://www.npmjs.com/package/snowflake-sdk?activeTab=versions

**Comment by sfc-gh-dszmolka** [comment] 2023-07-27 20:00
turns out the release is still in progress right as we speak and i was a bit too close to announce it's out. Indeed not yet published to npm. Let's give it a couple more hours.

**Comment by sfc-gh-dszmolka** [comment] 2023-07-28 06:10
Releng team hit a bump in the release process which will be continued on Monday as expected. Reopening the issue and will only close when artifact confirmed to published to npm. Apologies for the inconvenience.

**Comment by sfc-gh-dszmolka** [comment] 2023-07-28 17:09
PR is released as part of the latest Snowflake Node.JS driver version 1.7.0, for real this time :) Visible on `npm` too. Closing this issue and thank you for bearing with us !

**Closed by sfc-gh-dszmolka** 2023-07-28 17:09 UTC
Labels: bug, Fixed - Awaiting Release
