### ISSUE TITLE
Clearer diagnostics for non-existent database

### ISSUE THREAD

**Issue by ahwitz** [snowflakedb/snowflake-connector-nodejs#423] opened 2023-02-22 16:36 UTC
Please answer these questions before submitting your issue. Thanks!

> 1. What version of NodeJS are you using (`node --version` and `npm --version`)?

v16.15.0

> 2. What operating system and processor architecture are you using?

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19044 N/A Build 19044

> 3. What are the component versions in the environment (`npm list`)?

snowflake-sdk@1.6.18

> 4. What did you do?

```js
const connection = snowflake.createConnection({
  role,
  database,
  account,
  warehouse,
  username,
  password: '', // private key used instead, this property still required
  privateKey,
  authenticator: 'SNOWFLAKE_JWT',
  application: 'ARBITRARY'
});

await new Promise((resolve, reject) => {
  this[which + 'Connection'].connect(function (err, conn) {
    if (err) {
      console.error(err);
      reject('Unable to connect to Snowflake: ' + err.message);
    } else {
      console.log(
        `Successfully connected to Snowflake (${database} as ${which}).`
      );
      resolve(conn.getId());
    }
  });
});

await new Promise((resolve, reject) => {
 const options = {sqlText: `SELECT * FROM ${database}.INFORMATION_SCHEMA.SCHEMATA;`'};
  options.complete = (err, stmt, rows) => {
    if (rows) resolve(rows);
    if (err) reject(`During execution of: ${options.sqlText}: ` + err);
  };
  connection.execute(options);
});
```

Loose refactor of what we're working with. If this is called with `database = 'a_non_existent_database'`, we'd expect a loud failure during the connection process, but instead we get the following error when trying to run any query:

> OperationFailedError: Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.

I thought this was somehow related to the US-East-2 failure last night, and tried hardcoding a `USE DATABASE A_NON_EXISTENT_DATABASE;` call upon connection, after which we got a more descriptive error:

> OperationFailedError: SQL compilation error: Object does not exist, or operation cannot be performed.

> 5. What did you expect to see?

Connection fail when the database does not exist.

> 6. What did you see instead?

A misleading/inadequately descriptive error after a query is attempted.

**Comment by sfc-gh-dszmolka** [comment] 2023-02-24 07:55
hi, thank you for submitting this issue. at this moment, i cannot reproduce this problem. tried executing a basic 'connect to Snowflake + execute `SELECT 1`' script with the following scenarios:
* without specifying any `database` in `snowflake.createConnection` : `SELECT 1` was executed as expected
* specifying  `a_non_existent_database` in `snowflake.createConnection` : `SELECT 1` was executed as expected

(since `SELECT 1` does not need any database in the connection context, this is expected)

if you're still having the same issue even though the platform outage is over, to troubleshoot this further you think it would be possible to attach a working reproduction script, which when executed, leads to the error you're having ?
thank you in advance !

**Comment by ahwitz** [comment] 2023-03-14 14:45
Sorry for the delay on getting back, I hadn't run into this for a bit. It definitely is my overgeneralization - `SELECT 1` does work in cases where we're getting this error, but I just ran into another case where a role I was using the SDK as didn't have access to a database that I knew existed, and I got the same `USE DATABASE` error as before. I've replaced the `SELECT 1`; in the example code above with `SELECT * FROM ${database}.INFORMATION_SCHEMA.SCHEMATA;`, which should work in any database that the role has access to.

Probably better to rephrase the bug report as:
- We understand the security-by-obscurity-ish approach to giving a "that database does not exist" error instead of a "you do not have permissions to access that database."
- When that's the case, it'd be more helpful to receive an error saying "that database does not exist" instead of saying "you need to call `USE DATABASE` despite having already specified a database to use in the connection process."
- Per my answer to 5) above, if it's possible to bake that "that database does not exist" error into the connection process, that'd be great, but I understand why it may not be worthwhile (since queries like `SELECT 1` or queries against other databases may still work) or may break backwards-compatbility.

Definitely willing to accept this as a wontfix, but there was a moderate amount of lost developer time that wouldn't have been lost if the error wasn't "you need to call USE DATABASE" - for example, in Snowsight, if I run that `SELECT * FROM SCHEMATA` query, I get a `Database 'a_non_existent_database' does not exist or not authorized.`, which immediately tells me it's a permissions error instead of a bad query. That make more sense?

**Comment by sfc-gh-dszmolka** [comment] 2023-03-15 16:28
thank you for the clarification! however, the current behaviour is not driver-specific, it is coming from the Snowflake engine internals.

same test with the `non_existent_database` as the `database` context + executing `SELECT * FROM INFORMATION_SCHEMA.SCHEMATA` in this session.

1. [SnowSQL CLI](https://docs.snowflake.com/en/user-guide/snowsql) , Python-based 
```
$ ~/.snowsql/1.2.23/snowsql -a myaccount.prod3.us-west-2 -u admin -d non_existent_database -q 'SELECT * FROM INFORMATION_SCHEMA.SCHEMATA;'
* SnowSQL * v1.2.23
Type SQL statements or !help
090105 (22000): Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
Goodbye!
```

2. example Java program with the [Snowflake JDBC driver](https://docs.snowflake.com/en/user-guide/jdbc) (Bouncy Castle libs only for the keypair authentication, not relevant for this issue)
```
$ java -cp .:snowflake-jdbc-3.13.23.jar:bcpkix-jdk14-1.72.jar:bcprov-jdk14-1.72.jar TestJdbc.java
Exception in thread "main" net.snowflake.client.jdbc.SnowflakeSQLException: Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
  at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
  at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
  at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:456)
  at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:366)
  at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:464)
  at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:192)
  at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:129)
  at net.snowflake.client.core.SFStatement.execute(SFStatement.java:742)
  at net.snowflake.client.core.SFStatement.execute(SFStatement.java:652)
  at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:236)
  at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQuery(SnowflakeStatementV1.java:131)
  at TestJdbc.main(TestJdbc.java:76)
```

since this behaviour is not related for the snowflake-sdk library, I'm closing this issue here.

**Closed by sfc-gh-dszmolka** 2023-03-15 16:28 UTC
