### ISSUE TITLE
Support HTTP keep-alive

### ISSUE THREAD

**Issue by thoean** [snowflakedb/snowflake-connector-nodejs#47] opened 2019-07-09 08:44 UTC
JavaScript's default HTTPS agent has [http keep-alive turned off](https://nodejs.org/api/http.html#http_new_agent_options). This library uses a default https client with a few motifications to support proxies, see [code](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/agent/https_ocsp_agent.js).

We are running a bunch of scripts, in the thousands, and it took us roughly 5 minutes. The reason was that the socket wasn't kept alive in the underlying JavaScript client. We applied a hack on our side that changes the HTTPS agent of the snowflake-sdk library, but it's an ugly hack since we're overriding the prototype function of an internal class (which is subject to change with any version upgrade). This brought the execution down to less than 1min, a 10x improvement for our needs.

We'd like to inject the HTTPS agent when instantiating the snowflake-sdk instead, so something like `new Snowflake({ agent: myAgent, otherOptions: xxx })`.

I think one solution could be to not export an already instantiated `core` module in this library, but rather a class that can be constructed. This allows for more flexible usage of which underlying module is used, for the HTTPS agent, and for potentially other implementation aspects.

Anyway, as reference our hack:

```javascript
const SnowflakeHttpClient = require('snowflake-sdk/lib/http/node');
const httpsClient = require('https').Agent;
SnowflakeHttpClient.prototype.getAgentAndProxyOptions = function() {
  let agentClass = httpsClient;
  let agentOptions = { keepAlive: true };
  let options = { agentClass, agentOptions };
  return options;
};
```

**Comment by snowstakeda** [comment] 2019-11-26 19:58
Tested the change but appeared this will raise an exception:
```
select L_COMMENT from TPCH_SF100.LINEITEM limit 100000000
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
So far I have no idea how to address this. v1.4.0 will have some code change but `keepAlive` option disabled.

**Comment by thoean** [comment] 2019-11-26 20:41
Did you test with node v8 or higher? Current LTS is v12... just wanted to ensure we're not trying to find a bug due to an outdated (past end of life) node version. Thanks for sharing this context.

**Comment by snowstakeda** [comment] 2019-11-27 04:40
Tried v11 but got the same error.
```
   { Error: socket hang up
       at createHangUpError (_http_client.js:330:15)
       at Socket.socketOnEnd (_http_client.js:433:23)
       at Socket.emit (events.js:187:15)
       at endReadableNT (_stream_readable.js:1094:12)
       at process.internalTickCallback (internal/process/next_tick.js:72:19) code: 'ECONNRESET' } }
```
Selecting TPCH scale factor 100 LINEITEM for 100 and 100000 rows work well, but selecting 100000000 rows always fails in the middle.
Added retry for ECONNRESET but caused OOM randomly. Looks like memory leak is in somewhere in the retry code.

**Comment by thoean** [comment] 2019-11-27 16:43
Interesting. Good find. And the only difference is enabling keep alive in the https agent?

**Comment by smtakeda** [comment] 2019-11-27 16:59
yes. This is the place where `keepAlive` is set and the release candidate branch has `false`:
https://github.com/snowflakedb/snowflake-connector-nodejs/blob/prep-1.4.0/lib/http/node.js#L41

If this changes to `true`, `ECONNRESET` starts happening in the large result set test, which is not part of the bundled regression tests.

I suspect NodeJS Agent doesn't handle `ECONNERESET` properly, but In theory, since the connection is cut by the server, the retry should work, though, I could not dig into the point.

**Comment by thoean** [comment] 2019-12-15 17:23
It was super busy the last few days, and the link (branch) you reference above doesn't exist anymore. Or have those changes been merged in the meanwhile, and master reflects any changes you might have made since?

After some research (but no testing with this library), the httpKeepAlive works between connections, but not within the connection. There's the [httpRequest.setSocketKeepAlive](https://nodejs.org/api/http.html#http_request_setsocketkeepalive_enable_initialdelay) that might need to be set in addition to that. See https://github.com/nodejs/node/issues/16503 with an explanation from the NodeJS library directly (even though that's for an older version of Node, but I assume the fundamentals are still true).

**Comment by sfc-gh-dszmolka** [comment] 2023-05-25 06:48
should be resolved by https://github.com/snowflakedb/snowflake-connector-nodejs/pull/185 (except for the 'using proxy' cases, for which https://github.com/snowflakedb/snowflake-connector-nodejs/issues/491 is open)

**Closed by sfc-gh-dszmolka** 2023-05-25 06:48 UTC
Labels: enhancement, help wanted, jira
