### ISSUE TITLE
SNOW-1031704: The package is using an old version of @google-cloud/storage.

### ISSUE THREAD

**Issue by jainmohit2001** [snowflakedb/snowflake-connector-nodejs#759] opened 2024-01-31 15:29 UTC
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of NodeJS driver are you using?
snowflake-sdk@1.9.3
   
2. What operating system and processor architecture are you using?
WSL2 on Windows 10
   
3. What version of NodeJS are you using?
(`node --version` and `npm --version`)
v20.10.0

4. What are the component versions in the environment (`npm list`)?

5.Server version:* E.g. 1.90.1

6. What did you do?

Using snowflake-sdk with Next.js.

7. What did you expect to see?

No error while running `npm run build`.

I got the following error instead
```
./node_modules/@google-cloud/storage/node_modules/retry-request/index.js
Module not found: Can't resolve 'request' in '/path/to/node_modules/@google-cloud/storage/node_modules/retry-request'

Import trace for requested module:
./node_modules/@google-cloud/storage/node_modules/retry-request/index.js
./node_modules/@google-cloud/storage/build/src/nodejs-common/util.js
./node_modules/@google-cloud/storage/build/src/nodejs-common/index.js
./node_modules/@google-cloud/storage/build/src/bucket.js
./node_modules/@google-cloud/storage/build/src/index.js
./node_modules/snowflake-sdk/lib/file_transfer_agent/gcs_util.js
./node_modules/snowflake-sdk/lib/file_transfer_agent/remote_storage_util.js
./node_modules/snowflake-sdk/lib/file_transfer_agent/file_transfer_agent.js
./node_modules/snowflake-sdk/lib/connection/statement.js
./node_modules/snowflake-sdk/lib/connection/connection.js
./node_modules/snowflake-sdk/lib/core.js
./node_modules/snowflake-sdk/lib/snowflake.js
./node_modules/snowflake-sdk/index.js
./src/lib/db.ts
./src/components/navbar/actions.ts
./src/components/navbar/navbar.tsx
./src/app/(authorized)/layout.tsx
```

**Comment by sfc-gh-dszmolka** [comment] 2024-01-31 15:58
hi - thanks for submitting this issue ! 

can you please provide some details (like steps you execute) to get to this issue ? 

issuing `npm install` on a node v20.10.0 container successfully installs `@google-cloud/storage@6.12.0` per requirement in `package.json`. Thank you in advance  for the details!

**Comment by mohitric** [comment] 2024-02-01 08:39
Hi @sfc-gh-dszmolka
Here are the steps I used:

1) Install Next.js with basic minimal template https://nextjs.org/docs/getting-started/installation
2) Install snowflake-sdk using npm
3) Create a connection pool in a .ts file.
```typescript
import { Options as PoolOptions } from 'generic-pool'
import * as snowflake from 'snowflake-sdk'

const connectionOptions: snowflake.ConnectionOptions = {
  account: process.env.SNOWFLAKE_ACCOUNT!,
  database: process.env.SNOWFLAKE_DB,
  schema: process.env.SNOWFLAKE_SCHEMA,
  username: process.env.SNOWFLAKE_USERNAME,
  password: process.env.SNOWFLAKE_PASSWORD,
  warehouse: process.env.SNOWFLAKE_WAREHOUSE,
}

const poolOptions: PoolOptions = {
  max: 10,
  min: 2,
}

export const connectionPool = snowflake.createPool(
  connectionOptions,
  poolOptions,
)
```

4) Build the project using the following:
```bash
npm run build
```

You shall see the mentioned warnings in the console directly.

On another note, the npm package for @google-cloud/storage is currently at version 7.7.0 https://www.npmjs.com/package/@google-cloud/storage

It is a major version upgrade and I think the package should also upgrade the deps accordingly.

**Comment by jainmohit2001** [comment] 2024-02-01 08:40
Hi @sfc-gh-dszmolka
Here are the steps I used:

1) Install Next.js with basic minimal template https://nextjs.org/docs/getting-started/installation
2) Install snowflake-sdk using npm
3) Create a connection pool in a .ts file.
```typescript
import { Options as PoolOptions } from 'generic-pool'
import * as snowflake from 'snowflake-sdk'

const connectionOptions: snowflake.ConnectionOptions = {
  account: process.env.SNOWFLAKE_ACCOUNT!,
  database: process.env.SNOWFLAKE_DB,
  schema: process.env.SNOWFLAKE_SCHEMA,
  username: process.env.SNOWFLAKE_USERNAME,
  password: process.env.SNOWFLAKE_PASSWORD,
  warehouse: process.env.SNOWFLAKE_WAREHOUSE,
}

const poolOptions: PoolOptions = {
  max: 10,
  min: 2,
}

export const connectionPool = snowflake.createPool(
  connectionOptions,
  poolOptions,
)
```

4) Build the project using the following:
```bash
npm run build
```

You shall see the mentioned warnings in the console directly.

On another note, the npm package for @google-cloud/storage is currently at version 7.7.0 https://www.npmjs.com/package/@google-cloud/storage

It is a major version upgrade and I think the package should also upgrade the deps accordingly.

**Comment by jainmohit2001** [comment] 2024-02-01 09:38
Additional steps that might help us understand the error I am seeing:

1) Create a simple input form.
2) Create a Next.js Server action. Make sure to do some stuff using snowflake-sdk here. Just a call to the Database should suffice.
3) Call the server action on form submission.

... Error should appear in the console.

**Comment by sfc-gh-dszmolka** [comment] 2024-02-01 12:45
okay, so this requires a little bit more setup to mimic your specific environment :) for which, do you think it would be possible taking one of the two paths:
1. if possible, please create a full reproduction which when launched, produces the issue you're seeing. This can be shared either via a github repo, or attached here as a tarball, or something similar.
I know this requires additional resources, however since this issue seems to be very specific to certain framework, environment, and use-case - it's still the way forward.

**OR**

2. i created #760 (draft) to test if the version bump would instantly fail any tests; which it did not seem. Can you try to check out the fix branch from https://github.com/snowflakedb/snowflake-connector-nodejs/tree/test-bump-gcp-storage-to-7, use it as `snowflake-sdk` and see if it resolves the issue for you, in the same environment you're seeing the problem?

**Comment by jainmohit2001** [comment] 2024-02-01 13:39
Hi @sfc-gh-dszmolka. I'll try to share the repro soon.
I'll also try the bumped-up version.

**Comment by jainmohit2001** [comment] 2024-02-01 17:25
Hi @sfc-gh-dszmolka. 
Check this out https://github.com/googleapis/nodejs-storage/issues/2191

**Comment by jainmohit2001** [comment] 2024-02-02 05:46
Hi @sfc-gh-dszmolka.

Please find the minimal repro here https://github.com/jainmohit2001/snowflake-google-cloud-storage-issue

**Comment by sfc-gh-dszmolka** [comment] 2024-02-02 12:18
this is fantastic, thank you so much @jainmohit2001  ! issue can be very nicely reproduced using your repro, its clearly visible.

also happy to hear the fix branch helped you to tackle the issue, so I think it can use used as a workaround until we fix the issue properly. will keep this thread posted

**Comment by sfc-gh-dszmolka** [comment] 2024-02-05 07:41
PR #760 which bumps `@google-cloud/storage` to v7 is now merged, and will be part of the next driver release, expected around second half of February.

**Comment by sfc-gh-dszmolka** [comment] 2024-02-28 08:43
fix released with snowflake-sdk 1.10.0, closing this issue

**Closed by sfc-gh-dszmolka** 2024-02-28 08:43 UTC
Labels: bug, status-fixed_awaiting_release

**Comment by jainmohit2001** [comment] 2024-02-28 19:06
Hi @sfc-gh-dszmolka. Thanks for the release.
I upgraded the package and the error is now gone.

But I am seeing these messages in the console. Can you help me understand them and what they mean? If possible please share a link to the document where I can read more about this.

Thanks in advance!

```
{"level":"INFO","message":"[12:27:55.693 AM]: Trying to initialize Easy Logging"}
{"level":"INFO","message":"[12:27:55.706 AM]: Trying to initialize Easy Logging"}
{"level":"INFO","message":"[12:27:55.899 AM]: No client config file found in default directories"}
{"level":"INFO","message":"[12:27:55.900 AM]: Easy Logging is disabled as no config has been found"}
{"level":"INFO","message":"[12:27:55.921 AM]: No client config file found in default directories"}
{"level":"INFO","message":"[12:27:55.922 AM]: Easy Logging is disabled as no config has been found"}
```

**Comment by jainmohit2001** [comment] 2024-02-29 10:35
Thanks for the info!

I'll ignore them for now. I'll wait for the documentation first.
