### ISSUE TITLE
SNOW-792487 pool not passing back error on failed authentication

### ISSUE THREAD

**Issue by mbluemer** [snowflakedb/snowflake-connector-nodejs#470] opened 2023-04-13 15:37 UTC
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of NodeJS driver are you using?
`1.6.20`
   
2. What operating system and processor architecture are you using?
`MacOS Monterey 12.6.3, Intel architecture`
   
3. What version of NodeJS are you using?
(`node --version` and `npm --version`)
`16.17.0`

4. What are the component versions in the environment (`npm list`)?
```
├── babel-loader@8.2.5
├── core-js@3.25.5
├── generic-pool@3.9.0
├── http-errors@2.0.0
├── jsonwebtoken@9.0.0
├── moment@2.29.4
├── snowflake-sdk@1.6.20
├── supertest@6.2.4
├── ts-jest@28.0.8
├── ts-node@10.9.1
├── tslib@2.4.0
├── tslog@3.3.3
├── typescript@4.8.4
```

6.Server version:* E.g. 1.90.1

`7.12.3`

7. What did you do?

I ran the following snippet directly with node (`test.mjs` file) with an invalid username/password:
```
import snowflake from 'snowflake-sdk';

// Create the connection pool instance
const connectionPool = snowflake.createPool(
    // connection options
    {
	    account: account,
	    username: username,
	    password: password,
	    application: application,
	    database: database,
	    schema: schema,
	    warehouse: warehouse,
    },
    // pool options
    {
      max: 10, // specifies the maximum number of connections in the pool
      min: 0   // specifies the minimum number of connections in the pool
    }
);

try {
	const connection = await connectionPool.acquire();

	const statement = await connection.execute({
		sqlText: 'SELECT CURRENT_VERSION();',
		complete: function (err, stmt, rows)
		{
		    var stream = stmt.streamRows();
		    stream.on('data', function (row)
		    {
			console.log(row);
		    });
		    stream.on('end', function (row)
		    {
			console.log('All rows consumed');
		    });
		}
	});
} catch (err) {
	console.log('We caught the error');
	console.log(err);
}

```

9. What did you expect to see?

I expected to see "We caught the error" in the console but instead the program terminates before it reaches the catch block.

10. Can you set logging to DEBUG and collect the logs?

```
{"level":"DEBUG","message":"[11:36:50.3650 AM]: Contacting SF: /session/v1/login-request?requestId=97c7ead0-d4ad-4afb-b37b-b5d6e8e3e9c9&warehouse=DEV_WH&databaseName=TPC&schemaName=PUBLIC, (1/5)"}
{"level":"TRACE","message":"[11:36:50.3650 AM]: https://immuta.us-east-1.snowflakecomputing.com/session/v1/login-request?requestId=97c7ead0-d4ad-4afb-b37b-b5d6e8e3e9c9&warehouse=DEV_WH&databaseName=TPC&schemaName=PUBLIC"}
{"level":"DEBUG","message":"[11:36:50.3650 AM]: Reading OCSP cache file. /Users/mark.bluemer/Library/Caches/Snowflake/ocsp_response_cache.json"}
{"level":"TRACE","message":"[11:36:50.3650 AM]: Returning OCSP status for certificate 075A3D2D721433C0605B438A31E7767C from cache"}
{"level":"TRACE","message":"[11:36:50.3650 AM]: Returning OCSP status for certificate 077312380B9D6688A33B1ED9BF9CCDA68E0E0F from cache"}
{"level":"TRACE","message":"[11:36:50.3650 AM]: Returning OCSP status for certificate 067F944A2A27CDF3FAC2AE2B01F908EEB9C4C6 from cache"}
{"level":"TRACE","message":"[11:36:50.3650 AM]: Returning OCSP status for certificate A70E4A4C3482B77F from cache"}
{"level":"TRACE","message":"[11:36:51.3651 AM]: socket reused = false"}
{"level":"TRACE","message":"[11:36:51.3651 AM]: OCSP validation succeeded for immuta.us-east-1.snowflakecomputing.com"}

```

**Comment by sfc-gh-dszmolka** [comment] 2023-04-14 12:02
hi and thank you for raising this issue! i reproduced the issue thanks to your reproduction script. Ended up with
```
# node gh470.js
..
[2023-04-14T11:44:53.291Z] Unable to connect: Incorrect username or password was specified.
```

and indeed we don't reach the `catch` part. I believe the issue is happening in the `connectionPool.acquire()` part and perhaps should be handled there too.

`snowflake-sdk`'s `connectionPool` resource is no other than the generic [node-pool](https://github.com/coopernurse/node-pool#poolacquire) and if we look at the `pool.aquire()` description it suggests that a `Promise` is returned (either resolved if resource was acquired, or rejected if it wasn't) .

If the requirement here is to return an error upon a failed authentication, perhaps handling the `Promise` returned from `pool.aquire()` could be the way forward.

Closing this issue as it does not seem to be related to the `snowflake-sdk` but please feel free to comment if you found an issue with the Snowflake driver and I'll reopen it for you.

**Comment by mbluemer** [comment] 2023-04-14 14:14
@sfc-gh-dszmolka Thanks for taking a look, really appreciate the quick triage.

When using `await` the `catch` is what's used to handled the Promise returned from `pool.acquire()`.

I'll dig into the `snowflake-sdk` libraries code a little more to see what's going on but I really think this is a regression. We were previously using version `1.6.16` of the library, before the infinite loop on failure fix (https://github.com/snowflakedb/snowflake-connector-nodejs/commit/6ab19c2b230356fdb8bd2d0fb3ed4daea900bdf2) and our code was working just fine if we added the fix ourselves.

So, to be more precise, if you install `snowflake-sdk@1.6.16` and run the following snippet:
```
import snowflake from 'snowflake-sdk';

// Create the connection pool instance
const connectionPool = snowflake.createPool(
    // connection options
    {
	    account: account,
	    username: username,
	    password: password,
	    application: application,
	    database: database,
	    schema: schema,
	    warehouse: warehouse,
    },
    // pool options
    {
      max: 10, // specifies the maximum number of connections in the pool
      min: 0   // specifies the minimum number of connections in the pool
    }
);

connectionPool.on('factoryCreateError', (error) => {
        // Prevent the infinite loop when pool creation fails.
         connectionPool._waitingClientsQueue.dequeue().reject(error);
});

try {
	const connection = await connectionPool.acquire();

	const statement = await connection.execute({
		sqlText: 'SELECT CURRENT_VERSION();',
		complete: function (err, stmt, rows)
		{
		    var stream = stmt.streamRows();
		    stream.on('data', function (row)
		    {
			console.log(row);
		    });
		    stream.on('end', function (row)
		    {
			console.log('All rows consumed');
		    });
		}
	});
} catch (err) {
	console.log('We caught the error');
	console.log(err);
}
```
then we're successfully hitting the `catch` block.

**Comment by mbluemer** [comment] 2023-04-14 14:26
It looks like the problem is this line https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/core.js#L303 is missing `.reject(err)`

**Comment by sfc-gh-dszmolka** [comment] 2023-05-01 20:07
PR is merged into main, so will be part of the next release; to be expected in the second half of May

**Comment by sfc-gh-dszmolka** [comment] 2023-05-25 06:46
fix released with version [1.6.22](https://github.com/snowflakedb/snowflake-connector-nodejs/releases/tag/v1.6.22)

**Closed by sfc-gh-dszmolka** 2023-05-25 06:46 UTC
Labels: bug

**Comment by Lumengrid** [comment] 2024-02-05 17:49
Hi all,  how can we match the error message with the specific error code ?
Previously connecting directly we receive an snowflakeError in the the error promise with a code and we check, for example, the specific error code 390100 of the message Incorrect username or password was specified and match it for managing adhoc error to show. With the pool connection this is achievable in any way ?

`   const connection = await this.connectionPool.acquire().then((conn): snowflake.Connection => {
            this.logger.debug('* SNOWFLAKE CONNECTED * Successfully connected as id: ' + conn.getId());
            this.connectionErrorCode = '';
            return conn;
        }).catch((reason) => {
            this.logger.errorWithStack('* SNOWFLAKE ERROR * Unable to connect.', reason);
            this.connectionErrorCode = reason.code.toString();
            return false;
        });`

**Comment by sfc-gh-dszmolka** [comment] 2024-02-06 07:54
hi - i think this is is currently not possible, but tested with a patched `core.js` 
```js
--- core.js.original	2024-02-06 07:47:27.346468341 +0000
+++ node_modules/snowflake-sdk/lib/core.js	2024-02-06 07:46:45.391737771 +0000
@@ -249,7 +249,7 @@
           function (err, conn) {
             if (err) {
               Logger.getInstance().error('Unable to connect: ' + err.message);
-              reject(new Error(err.message));
+              reject(err);
             } else {
               resolve(conn);
             }

```

and it would reject the pool Promise with more info:
```
{"level":"ERROR","message":"[7:49:17.603 AM]: Unable to connect: Incorrect username or password was specified."}
Error [OperationFailedError]: Incorrect username or password was specified.
    at createError (/test/node_modules/snowflake-sdk/lib/errors.js:526:17)
    at exports.createOperationFailedError (/test/node_modules/snowflake-sdk/lib/errors.js:329:10)
    at Object.callback (/test/node_modules/snowflake-sdk/lib/services/sf.js:626:28)
    at /test/node_modules/snowflake-sdk/lib/http/base.js:42:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: '390100',
  data: { nextAction: 'RETRY_LOGIN', authnMethod: 'USERNAME_PASSWORD' }
}
```

where it has the error `code` too. (by the way there's a list of error codes/messages in the [constants](https://github.com/snowflakedb/snowflake-connector-nodejs/tree/master/lib/constants) and there's a `snowflake-sdk` independent project to investigate if and how we could expose the Snowflake-internal error messages like `390100`)

But back to the original topic. Changing the current error structure and behaviour is not impossible of course, but would be considered a breaking change very likely, so it would require a use-case where the error message available is not enough to determine where the error is - can you perhaps provide more insight why this would be necessary ?
