### ISSUE TITLE
SNOW-750114: Please consider removing the "urllib" dependency

### ISSUE THREAD

**Issue by cweijan** [snowflakedb/snowflake-connector-nodejs#426] opened 2023-02-27 07:19 UTC
When I start using snowflake-sdk, the console will appear `(node:38280) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`.

After my investigation, it is because urllib indirectly references a large number of dependencies that are no longer maintained, and they use `new Buffer()`, which is no longer recommended. Snowflake-sdk uses urllib only Send http request, please consider using other dependencies instead.

**Comment by sfc-gh-dszmolka** [comment] 2023-02-28 07:07
duplicate of:
* https://github.com/snowflakedb/snowflake-connector-nodejs/issues/357

**Closed** 2023-02-28 07:07 UTC
