### ISSUE TITLE
"async" is declared as devDependency but used outside test codes

### ISSUE THREAD

**Issue by wei-beamery** [snowflakedb/snowflake-connector-nodejs#411] opened 2023-01-30 01:06 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
node v16.19.0
npm 8.19.3

3. What operating system and processor architecture are you using?

Mac Ventura 13.2

4. What are the component versions in the environment (`npm list`)?
1.6.11

6. What did you do?
Installed this lib

7. What did you expect to see?
Dependencies are declared correctly

8. What did you see instead?
Non-dev dependency "async" was declared as dev dependency

10. Add this to get standard output.
 
```
var snowflake = require('./snowflake');
snowflake.configure(
{
  logLevel: 'trace'
});
```

**Comment by sfc-gh-dszmolka** [comment] 2023-01-30 10:52
closing this as a duplicate of #394 . please feel free to reopen if you feel it is not related to the Issue discussed in the linked one.

**Closed by sfc-gh-dszmolka** 2023-01-30 10:52 UTC
