### ISSUE TITLE
Connection crashes when run inside AWS Lambda

### ISSUE THREAD

**Issue by pulpfree** [snowflakedb/snowflake-connector-nodejs#401] opened 2023-01-19 16:44 UTC
1. What version of NodeJS are you using (`node --version` and `npm --version`)?
node --version = v18.12.1
npm --version = 8.19.2

2. What operating system and processor architecture are you using?
AWS Lambda x86_64
MacOS 13.1

3. What are the component versions in the environment (`npm list`)?
├── @apollo/server@4.3.0
├── @as-integrations/aws-lambda@1.1.0
├── @gar/promisify@1.1.3 extraneous
├── @graphql-codegen/cli@2.16.4
├── @graphql-codegen/typescript-resolvers@2.7.12
├── @graphql-codegen/typescript@2.8.7
├── @isaacs/string-locale-compare@1.1.0 extraneous
├── @npmcli/arborist@6.1.6 extraneous
├── @npmcli/config@6.1.1 extraneous
├── @npmcli/disparity-colors@3.0.0 extraneous
├── @npmcli/fs@3.1.0 extraneous
├── @npmcli/git@4.0.3 extraneous
├── @npmcli/installed-package-contents@2.0.1 extraneous
├── @npmcli/map-workspaces@3.0.1 extraneous
├── @npmcli/metavuln-calculator@5.0.0 extraneous
├── @npmcli/move-file@2.0.1 extraneous
├── @npmcli/name-from-folder@1.0.1 extraneous
├── @npmcli/node-gyp@3.0.0 extraneous
├── @npmcli/package-json@3.0.0 extraneous
├── @npmcli/promise-spawn@6.0.2 extraneous
├── @npmcli/query@3.0.0 extraneous
├── @npmcli/run-script@6.0.0 extraneous
├── @types/aws-lambda@8.10.109
├── @types/jest@29.2.6
├── @types/lodash-es@4.17.6
├── @types/node@18.11.18
├── @types/snowflake-sdk@1.6.12
├── @typescript-eslint/eslint-plugin@5.48.1
├── @typescript-eslint/parser@5.48.1
├── agentkeepalive@4.2.1 extraneous
├── aproba@2.0.0 extraneous
├── archy@1.0.0 extraneous
├── are-we-there-yet@4.0.0 extraneous
├── bin-links@4.0.1 extraneous
├── builtins@5.0.1 extraneous
├── cacache@17.0.4 extraneous
├── chownr@2.0.0 extraneous
├── cidr-regex@3.1.1 extraneous
├── cli-columns@4.0.0 extraneous
├── cli-table3@0.6.3 extraneous
├── cmd-shim@6.0.1 extraneous
├── color-support@1.1.3 extraneous
├── columnify@1.6.0 extraneous
├── common-ancestor-path@1.0.1 extraneous
├── console-control-strings@1.1.0 extraneous
├── cssesc@3.0.0 extraneous
├── delegates@1.0.0 extraneous
├── env-paths@2.2.1 extraneous
├── err-code@2.0.3 extraneous
├── esbuild-jest@0.5.0
├── esbuild@0.14.54
├── eslint-config-prettier@8.6.0
├── eslint-plugin-prettier@4.2.1
├── eslint@8.31.0
├── fastest-levenshtein@1.0.16 extraneous
├── fs-minipass@2.1.0 extraneous
├── gauge@5.0.0 extraneous
├── generic-pool@3.9.0
├── graphql@16.6.0
├── has-unicode@2.0.1 extraneous
├── hosted-git-info@6.1.1 extraneous
├── http-cache-semantics@4.1.0 extraneous
├── ignore-walk@6.0.0 extraneous
├── infer-owner@1.0.4 extraneous
├── ini@3.0.1 extraneous
├── init-package-json@4.0.1 extraneous
├── install@0.13.0
├── ip-regex@4.3.0 extraneous
├── is-cidr@4.0.2 extraneous
├── is-lambda@1.0.1 extraneous
├── jest@29.3.1
├── json-parse-even-better-errors@3.0.0 extraneous
├── json-stringify-nice@1.1.4 extraneous
├── jsonparse@1.3.1 extraneous
├── just-diff-apply@5.5.0 extraneous
├── just-diff@5.2.0 extraneous
├── libnpmaccess@7.0.1 extraneous
├── libnpmdiff@5.0.7 extraneous
├── libnpmexec@5.0.7 extraneous
├── libnpmfund@4.0.7 extraneous
├── libnpmhook@9.0.1 extraneous
├── libnpmorg@5.0.1 extraneous
├── libnpmpack@5.0.7 extraneous
├── libnpmpublish@7.0.6 extraneous
├── libnpmsearch@6.0.1 extraneous
├── libnpmteam@5.0.1 extraneous
├── libnpmversion@4.0.1 extraneous
├── lodash-es@4.17.21
├── make-fetch-happen@11.0.2 extraneous
├── minipass-collect@1.0.2 extraneous
├── minipass-fetch@3.0.1 extraneous
├── minipass-flush@1.0.5 extraneous
├── minipass-json-stream@1.0.1 extraneous
├── minipass-pipeline@1.2.4 extraneous
├── minipass-sized@1.0.3 extraneous
├── minipass@3.3.6 extraneous
├── minizlib@2.1.2 extraneous
├── node-gyp@9.3.1 extraneous
├── nodemon@2.0.20
├── nopt@7.0.0 extraneous
├── normalize-package-data@5.0.0 extraneous
├── npm-audit-report@4.0.0 extraneous
├── npm-bundled@3.0.0 extraneous
├── npm-install-checks@6.0.0 extraneous
├── npm-normalize-package-bin@3.0.0 extraneous
├── npm-package-arg@10.1.0 extraneous
├── npm-packlist@7.0.4 extraneous
├── npm-pick-manifest@8.0.1 extraneous
├── npm-profile@7.0.1 extraneous
├── npm-registry-fetch@14.0.3 extraneous
├── npm-user-validate@1.0.1 extraneous
├── npm@9.3.0
├── npmlog@7.0.1 extraneous
├── pacote@15.0.8 extraneous
├── parse-conflict-json@3.0.0 extraneous
├── postcss-selector-parser@6.0.11 extraneous
├── prettier@2.8.2
├── proc-log@3.0.0 extraneous
├── promise-all-reject-late@1.0.1 extraneous
├── promise-call-limit@1.0.1 extraneous
├── promise-inflight@1.0.1 extraneous
├── promise-retry@2.0.1 extraneous
├── promzard@0.3.0 extraneous
├── qrcode-terminal@0.12.0 extraneous
├── read-cmd-shim@4.0.0 extraneous
├── read-package-json-fast@3.0.2 extraneous
├── read-package-json@6.0.0 extraneous
├── read@1.0.7 extraneous
├── snowflake-sdk@1.6.17
├── spdx-correct@3.1.1 extraneous
├── spdx-exceptions@2.3.0 extraneous
├── spdx-expression-parse@3.0.1 extraneous
├── spdx-license-ids@3.0.12 extraneous
├── ssri@10.0.1 extraneous
├── tar@6.1.13 extraneous
├── tiny-relative-date@1.3.0 extraneous
├── treeverse@3.0.0 extraneous
├── ts-node@10.9.1
├── typescript@4.9.4
├── unique-filename@3.0.0 extraneous
├── unique-slug@4.0.0 extraneous
├── validate-npm-package-license@3.0.4 extraneous
├── validate-npm-package-name@5.0.0 extraneous
├── walk-up-path@1.0.0 extraneous
├── which@3.0.0 extraneous
├── wide-align@1.1.5 extraneous
└── write-file-atomic@5.0.0 extraneous

4. What did you do?

Here is my connection code:
```
import snowflake from 'snowflake-sdk'
snowflake.configure({ logLevel: 'TRACE' })

import cfg from '../config/snowflake.js'

const connection = snowflake.createConnection({
  account: cfg.account,
  username: cfg.username,
  password: cfg.password,
  database: cfg.database,
  schema: cfg.schema,
  warehouse: cfg.warehouse,
})

connection.connect(function (err, conn) {
  if (err) {
    console.error('Unable to connect: ' + err.message)
  } else {
    console.log('Successfully connected to Snowflake.')
    console.log('conn.getId(): ', conn.getId())
  }
})
```
5. What did you expect to see?

I'm getting a successful connection when running in a 'stand-alone server' (outside of lambda) and am able to do basic query.

```
connection time: 1.748ms
{"level":"DEBUG","message":"[11:31:58.3158 AM]: Contacting SF: /session/v1/login-request?requestId=e7e5bb9f-76ec-432b-805f-ac7c3d855066&warehouse=SAVVIE_TEST_WH&databaseName=SAVVIE_TEST&schemaName=SAVVIE, (1/5)"}
{"level":"TRACE","message":"[11:31:58.3158 AM]: https://jyzpppq-vyb20311.snowflakecomputing.com/session/v1/login-request?requestId=e7e5bb9f-76ec-432b-805f-ac7c3d855066&warehouse=SAVVIE_TEST_WH&databaseName=SAVVIE_TEST&schemaName=SAVVIE"}
🚀 Server listening at: http://localhost:4000/
{"level":"DEBUG","message":"[11:31:59.3159 AM]: Reading OCSP cache file. /Users/rondyck/Library/Caches/Snowflake/ocsp_response_cache.json"}
{"level":"TRACE","message":"[11:31:59.3159 AM]: Returning OCSP status for certificate 0ED55484709E345D0191C9A9DF222914 from cache"}
{"level":"TRACE","message":"[11:31:59.3159 AM]: Returning OCSP status for certificate 067F94578587E8AC77DEB253325BBC998B560D from cache"}
{"level":"TRACE","message":"[11:31:59.3159 AM]: Returning OCSP status for certificate 067F944A2A27CDF3FAC2AE2B01F908EEB9C4C6 from cache"}
{"level":"TRACE","message":"[11:31:59.3159 AM]: Returning OCSP status for certificate A70E4A4C3482B77F from cache"}
{"level":"TRACE","message":"[11:31:59.3159 AM]: socket reused = false"}
{"level":"TRACE","message":"[11:31:59.3159 AM]: OCSP validation succeeded for jyzpppq-vyb20311.snowflakecomputing.com"}
Successfully connected to Snowflake.
conn.getId():  f41bba58-9218-4457-b5cb-135fd4fe2a8d
```

However,  the problem is when running in a lambda, either testing locally or when deployed:
```
2023-01-19 11:33:53  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
Invoking app.graphqlHandler (nodejs18.x)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-nodejs18.x:rapid-1.67.0-x86_64.

Mounting /Users/rondyck/Projects/SavvieMVP/api/.aws-sam/build/GraphqlFunction as /var/task:ro,delegated inside runtime container
START RequestId: 0b2bf401-a485-4e0b-85b8-3f970f63e832 Version: $LATEST

<--- Last few GCs --->
li[15:0x55cdf70eefd0]     3703 ms: Mark-sweep (reduce) 229.9 (235.1) -> 229.9 (235.1) MB, 81.8 / 0.0 ms  (+ 1.9 ms in 2 steps since start of marking, biggest step 1.9 ms, walltime since start of marking 90 ms) (average mu = 0.303, current mu = 0.253) alloca[15:0x55cdf70eefd0]     3792 ms: Mark-sweep (reduce) 229.9 (235.1) -> 229.9 (235.1) MB, 66.7 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 67 ms) (average mu = 0.283, current mu = 0.254) alloca

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x55cdf146d7c3 node::Abort() [/var/lang/bin/node]
 2: 0x55cdf133db32  [/var/lang/bin/node]
 3: 0x55cdf169290d v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/var/lang/bin/node]
 4: 0x55cdf1692c12 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/var/lang/bin/node]
 5: 0x55cdf18cf8e8  [/var/lang/bin/node]
 6: 0x55cdf18d09ea v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/var/lang/bin/node]
 7: 0x55cdf18e14cd v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [/var/lang/bin/node]
 8: 0x55cdf18e2636 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/var/lang/bin/node]
 9: 0x55cdf18e5011 v8::internal::Heap::CollectAllAvailableGarbage(v8::internal::GarbageCollectionReason) [/var/lang/bin/node]
10: 0x55cdf18b5581 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/var/lang/bin/node]
11: 0x55cdf18901f6 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/var/lang/bin/node]
12: 0x55cdf1d00104 v8::internal::Runtime_AllocateInOldGeneration(int, unsigned long*, v8::internal::Isolate*) [/var/lang/bin/node]
13: 0x55cdf21e2339  [/var/lang/bin/node]
19 Jan 2023 16:35:36,492 [ERROR] (rapid) Init failed error=Runtime exited with error: signal: aborted InvokeID=
```

I had similar connection problems when creating a connection pool, and so I thought I'd get more basic with a straight connection, but no luck.

Ron

**Comment by sfc-gh-dszmolka** [comment] 2023-01-21 14:33
hi, not sure what the problem might be in your case. many people here reported various issues related to the node.js driver running in AWS Lambda (e.g. deprecation warnings, etc) which means it does run in Lambda :) 

for now in a reproduction attempt, i created a `node:18` image containing a simplistic script, which connects to Snowflake and executed `select current_user()`. uploaded to ECR and created a Lambda function of it. it works correctly when invoked; connects to Snowflake and executes the query.

google search against this issue suggests people increasing the `max_old_space_size` through `NODE_OPTIONS` , you can try that and see if it helps you.

otherwise if you believe this issue is specifically related to the Snowflake node.js driver and not the execution environment, could you please provide steps for reproduction  so we could debug further ? thank you in advance !

**Comment by deepak-panwar-paf** [comment] 2023-01-23 13:43
I'm running into the same issue in aws lambda

**Comment by sfc-gh-dszmolka** [comment] 2023-01-23 13:47
@deepak-panwar-paf can you (or @pulpfree) by any chance provide an exact reproduction scenario, how to get to this issue? as seen above, i didn't manage to reproduce it for myself, but maybe i didn't try the same way as you guys do. 

providing a reproducible scenario (with environment setup, steps to execute, etc) would greatly help with troubleshooting. thank you in advance !

**Comment by pulpfree** [comment] 2023-01-23 18:25
I'm using a basic AWS SAM template using NodeJS and TypeScript. I'm wondering if TS and the esbuild build method process may be at the source of this issue.

I've created a [repo here](https://github.com/savvie-com/snowflake-lambda) with instructions in the [SETUP doc](https://github.com/savvie-com/snowflake-lambda/blob/master/SETUP.md) for how to reproduce the scenario.

Essentially the steps entail the following:

1. sam init
1. Which template source -- 1 - AWS Quick Start...
1. Choose an AWS Quick Start -- 1 - Hello World...
1. Use the most popular runtime -- N
1. Which runtime would... -- 12 - nodejs18.x
1. What package type... -- 1 - Zip
1. Select your starter template -- 2 - Hellow World Example TypeScript
1. Would you like to enable X-Ray... -- y
1. Would you like to enable monitoring using... -- y
1. Project name -- snowflake-lambda

```bash
cd snowflake-lambda/hello-world
yarn
yarn add snowflake-sdk
yarn add -D @types/snowflake-sdk
```

Add the following code to the app.ts file:

```typescript
const connection = snowflake.createConnection({
    account: 'account',
    username: 'username',
    password: 'password',
    database: 'database',
    schema: 'schema',
    warehouse: 'warehouse',
});
connection.connect(function (err, conn) {
    if (err) {
        console.error('Unable to connect: ' + err.message);
    } else {
        console.log('Successfully connected to Snowflake.');
        // Optional: store the connection ID.
        // connection_ID = conn.getId()
        console.log('conn.getId(): ', conn.getId());
    }
});
```

Replace connection parameters

Build and run:
`sam build && sam local start-api`

**Comment by sfc-gh-dszmolka** [comment] 2023-01-24 11:20
this is awesome, thank you for providing the detailed reproduction! following the steps, i got to the following results
1. needed to move `esbuild` to dependencies (out from `devDependencies) for a successful build
2. indeed `sam local start-api` or `sam local invoke` fails with the aforementioned error
```
24 Jan 2023 10:57:07,048 [ERROR] (rapid) Init failed error=Runtime exited with error: signal: killed InvokeID=
```
3. then i modified the `template.yaml` (auto-generated by `sam init` i guess) and added `MemorySize: 256` (default: 128) under `Resources.HelloWorldFunction.Properties`, by default this property is not included. So looks like this now:
```yaml
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      MemorySize: 256 # <<< newly added line
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
..rest of the pre-existing stuff..
```
4. `sam build` again, then `sam local invoke`, now fails with something entirely different:
```
$ sam --debug local invoke 
2023-01-24 11:54:41,321 | Return available internal hook packages
2023-01-24 11:54:41,325 | Return available internal hook packages
Invoking app.lambdaHandler (nodejs18.x)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-nodejs18.x:rapid-1.70.1-x86_64.

Mounting /my/path/to/node/snowflake-lambda-ts/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: 5385d77c-47e4-49f8-b9a5-67e6b82ceda8 Version: $LATEST
2023-01-24T10:54:43.454Z	undefined	ERROR	Uncaught Exception 	{"errorType":"ReferenceError","errorMessage":"maskedtxt is not defined","stack":["ReferenceError: maskedtxt is not defined","    at Qlt.Qlt.maskSecrets (/private/var/folders/wb/zfcj89152_v46tl_b2ccjbs80000gn/T/tmp03rr12za/node_modules/snowflake-sdk/lib/secret_detector.js:175:7)","    at log (/private/var/folders/wb/zfcj89152_v46tl_b2ccjbs80000gn/T/tmp03rr12za/node_modules/snowflake-sdk/lib/logger/core.js:313:32)","    at Object.debug (/private/var/folders/wb/zfcj89152_v46tl_b2ccjbs80000gn/T/tmp03rr12za/node_modules/snowflake-sdk/lib/logger/core.js:224:9)","    at D2r.D2r.debug (/private/var/folders/wb/zfcj89152_v46tl_b2ccjbs80000gn/T/tmp03rr12za/node_modules/snowflake-sdk/lib/logger/node.js:126:18)","    at sendRequest (/private/var/folders/wb/zfcj89152_v46tl_b2ccjbs80000gn/T/tmp03rr12za/node_modules/snowflake-sdk/lib/services/sf.js:1196:26)","    at Vm.Vm.continue (/private/var/folders/wb/zfcj89152_v46tl_b2ccjbs80000gn/T/tmp03rr12za/node_modules/snowflake-sdk/lib/services/sf.js:1209:3)","    at Vm.Vm.enter (/private/var/folders/wb/zfcj89152_v46tl_b2ccjbs80000gn/T/tmp03rr12za/node_modules/snowflake-sdk/lib/services/sf.js:1021:8)","    at transitionTo (/private/var/folders/wb/zfcj89152_v46tl_b2ccjbs80000gn/T/tmp03rr12za/node_modules/snowflake-sdk/lib/services/sf.js:159:20)","    at KUe.KUe.transitionToConnecting (/private/var/folders/wb/zfcj89152_v46tl_b2ccjbs80000gn/T/tmp03rr12za/node_modules/snowflake-sdk/lib/services/sf.js:180:5)","    at mf.mf.connect (/private/var/folders/wb/zfcj89152_v46tl_b2ccjbs80000gn/T/tmp03rr12za/node_modules/snowflake-sdk/lib/services/sf.js:967:25)"]}
24 Jan 2023 10:54:43,551 [ERROR] (rapid) Init failed InvokeID= error=Runtime exited with error: exit status 129
Function 'HelloWorldFunction' timed out after 3 seconds
END RequestId: 905b2d13-826c-4975-9162-c84847fb1be7
REPORT RequestId: 905b2d13-826c-4975-9162-c84847fb1be7	Init Duration: 0.19 ms	Duration: 3000.00 ms	Billed Duration: 3000 ms	Memory Size: 256 MB	Max Memory Used: 256 MB	
No response from invoke container for HelloWorldFunction
```

looks like now it could pass the previous phase and get to a point where the script itself errors out with the `ReferenceError` , which I believe is not related to the original `Reached heap limit Allocation failed - JavaScript heap out of memory` error.
5. redid the whole reproduction, except that at step7 the starter template selection, I chose the non-TypeScript version
6. when the function was invoked this time after rebuild:
```
$ sam --debug local invoke
2023-01-24 12:13:04,584 | Return available internal hook packages
2023-01-24 12:13:04,589 | Return available internal hook packages
Invoking app.lambdaHandler (nodejs18.x)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-nodejs18.x:rapid-1.70.1-x86_64.

Mounting /my/path/to/node/snowflake-lambda-js/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: 5d8d9701-db92-44fa-bf19-d9fbc7cd060a Version: $LATEST
Function 'HelloWorldFunction' timed out after 3 seconds
No response from invoke container for HelloWorldFunction
```

No init/memory error and also no `ReferenceError` which I believe might come from the types.

To me as a conclusion, all of this tells that the original problem described in this Issue might be related to not enough memory being available for the function, which could be avoided by allocating more memory (`MemorySize: 256` instead of the default 'option not present' which means 128 megs) in the environment.

Could you please check it and see if it helps in your case ?

**Comment by sher04lock** [comment] 2023-01-24 12:38
I think this ReferenceError: 
```
{"errorType":"ReferenceError","errorMessage":"maskedtxt is not defined","stack":["ReferenceError: maskedtxt is not defined","    at Qlt.Qlt.maskSecrets (/private/var/folders/wb/zfcj89152_v46tl_b2ccjbs80000gn/T/tmp03rr12za/node_modules/snowflake-sdk/lib/secret_detector.js:175:7)","
```

Is because `masktxt` is defined as global variable in `secret_detector.js` file (which doesn't seem to be good approach anyway...) and esbuild can't see this variable.
I was able to temporarily fix it by declaring it at the beginning of maskSecrets function:

```
 this.maskSecrets = function (text) {
    var result;
    if (!text) {
      result =
      {
        masked: false,
        maskedtxt: text,
        errstr: null
      };
      return result;
    }

    var masked = false;
    var maskedtxt; // <------------------- added
    var errstr = null;
```

I'm working on another repro example, in my case establishing connection to Snowflake is measured in minutes when ran on AWS Lambda.

**Comment by sfc-gh-dszmolka** [comment] 2023-01-24 13:17
@sher04lock appreciate for the fix ! however , i recommend not mixing issues up. the function not being able to start at all (and instead, crashing) is probably not related to what you experience, lambda taking minutes to establish the connection to Snowflake.

(also possibly not related to Snowflake at all, but instead to the 'cold starts', see for example https://aws.amazon.com/blogs/compute/operating-lambda-performance-optimization-part-1/ )

**Comment by pulpfree** [comment] 2023-01-24 16:18
After adding additional memory and extending the timeout (in the template.yaml file)

```
Globals:
  Function:
    Timeout: 10 <-- increased from 3 to 10
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 512 <-- add line
      Architectures:
      - x86_64
     ...
```

I received the following error from the connect function
` ERROR   (node:14) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer(Use `node --trace-deprecation ...` to show where the warning was created)`

At 256mb of memory I continued to get `JavaScript heap out of memory` so increased memory and then received a timeout similar to @sfc-gh-dszmolka

In entirety, the return with 512 Mb and a 10 second timeout was:

```
 sam --debug local invoke HelloWorldFunction --event events/event.json
2023-01-24 11:04:54,374 | Return available internal hook packages
2023-01-24 11:04:54,380 | Return available internal hook packages
Invoking app.lambdaHandler (nodejs18.x)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-nodejs18.x:rapid-1.70.0-x86_64.

Mounting /Users/rondyck/Projects/SavvieMVP/testapi/snowflake-lambda/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: 3f8c462b-4747-49b0-9ecb-6b466bf6a690 Version: $LATEST
2023-01-24T16:04:57.618Z        undefined       INFO    connection time: 20.414ms
2023-01-24T16:04:57.725Z        undefined       ERROR   (node:14) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer(Use `node --trace-deprecation ...` to show where the warning was created)
END RequestId: 3f8c462b-4747-49b0-9ecb-6b466bf6a690
REPORT RequestId: 3f8c462b-4747-49b0-9ecb-6b466bf6a690  Init Duration: 0.20 ms  Duration: 2679.58 ms    Billed Duration: 2680 ms        Memory Size: 512 MB     Max Memory Used: 512 MB
{"statusCode":200,"body":"{\"message\":\"hello world\"}"}%  
```

The connection code in app.ts is:
```
console.time('connection time');
const connection = snowflake.createConnection({
    account: '===,'
    username: '===',
    password: '===',
    database: '===',
    schema: '=',
    warehouse: '=',
});
connection.connect(function (err, conn) {
    if (err) {
        console.error('Unable to connect: ' + err.message);
    } else {
        console.log('Successfully connected to Snowflake.');
        // Optional: store the connection ID.
        // connection_ID = conn.getId()
        console.log('conn.getId(): ', conn.getId());
    }
});
console.timeEnd('connection time');
```

**Comment by sfc-gh-dszmolka** [comment] 2023-01-24 16:45
nice 👍  thank you for sharing the full solution @pulpfree !
the
```
ERROR   (node:14) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer
```

is due to #363 / #357  and will be addressed once urllib is be bumped. 
with that said, i'm closing this issue but please feel free to reopen if further help is needed on the same issue.

**Closed by sfc-gh-dszmolka** 2023-01-24 16:45 UTC
