### ISSUE TITLE
SNOW-577970: require-ing package not declared in the package.json

### ISSUE THREAD

**Issue by akhilnaik** [snowflakedb/snowflake-connector-nodejs#293] opened 2022-04-19 05:11 UTC
I have found that the module 'bn.js' which is required in cert_util.js is not declared in the package.json
Doing a `npm ci --production` in my package followed by `npm start` throws an error:

`/Users/akhilnaik/workspace/*project-path*/node_modules/*private-dependency*/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: Cannot find module 'bn.js'
Require stack:
- /Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/agent/cert_util.js
- /Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/agent/check.js
- /Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/agent/socket_util.js
- /Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/agent/https_ocsp_agent.js
- /Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/http/node.js
- /Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/snowflake.js
- /Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/index.js
- /Users/akhilnaik/workspace/*project-path*/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/agent/cert_util.js:36:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/agent/check.js:35:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/agent/cert_util.js',
    '/Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/agent/check.js',
    '/Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/agent/socket_util.js',
    '/Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/agent/https_ocsp_agent.js',
    '/Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/http/node.js',
    '/Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/lib/snowflake.js',
    '/Users/akhilnaik/workspace/*project-path*/node_modules/snowflake-sdk/index.js',
    '/Users/akhilnaik/workspace/*project-path*/server.js'
  ],
  time: 2022-04-19T04:52:16.158Z
}`

'bn.js' require is present at:
https://github.com/snowflakedb/snowflake-connector-nodejs/blob/5713d2f19a6d6c27593ad99a71c47074bb6796c9/lib/agent/cert_util.js#L36

node version: v14.18.1
npm version: v8.6.0

**Comment by sfc-gh-dszmolka** [comment] 2023-01-18 08:58
thank you for reporting this issue. #293 and #343 look similar, in a way that both of them are caused by the missing dependencies. seems to be still missing in the latest version of the driver (1.6.17 now), we'll take a look.

**Comment by rezoled** [comment] 2023-03-26 15:36
Any update on this? This broke our build.
The file here:
https://github.com/snowflakedb/snowflake-connector-nodejs/blob/89b7ec4408ab29d978d9be9dc7cd23463f7236f0/lib/agent/cert_util.js#L36
is importing bn.js which is not declared in package.json.

Temporary fix is to install bn.js ourselves in our project. 
This is NOT a goos solution since we have no idea on version compatabilty with snowflake-sdk's usage.

Sidenote - If you are using a package pruning library (like NX) it will remove bn.js dependecy since it can't find any project that uses it, the solution is to just arbitrarily import 'bn.js' into your project in any of your files:
```import 'bn.js';```

**Comment by sfc-gh-dszmolka** [comment] 2023-03-26 18:41
no updates as of now, other issues took priority. this is fairly straightforward to fix, so hopefully the team can get to it. will post any news here, once they're available.

**Comment by smhdfdl** [comment] 2023-04-25 10:21
@sfc-gh-dszmolka we are also encountering this issue, what is the timeline for a fix please?

**Comment by smhdfdl** [comment] 2023-04-25 15:01
@sfc-gh-dszmolka It would be helpful to know what version of `bin.js` we should be adding as a workaround.

**Comment by sfc-gh-dszmolka** [comment] 2023-04-25 15:36
> @sfc-gh-dszmolka It would be helpful to know what version of `bin.js` we should be adding as a workaround.

considering it's also a requirement of `asn1.js` , i think you can try to use the same version constraint which is specified in the [asn1.js package.json](https://github.com/indutny/asn1.js/blob/v5.4.1/package.json#L31)
```json
"bn.js": "^4.0.0",
```

**Comment by sfc-gh-dszmolka** [comment] 2023-05-25 06:44
fix released with version [1.6.22](https://github.com/snowflakedb/snowflake-connector-nodejs/releases/tag/v1.6.22)

**Closed by sfc-gh-dszmolka** 2023-05-25 06:44 UTC
Labels: bug
